from collections.abc import Iterator, Sequence
from os import PathLike
from pathlib import Path
from typing import Any, Self

from ._index import IndexFile

class IgnoreSearch:
    @staticmethod
    def from_overrides(patterns: Sequence[str | bytes], *, support_precious: bool = False) -> IgnoreSearch: ...

class AttributeStack:
    def base(self) -> Path: ...
    def at_path(self, relative: str | PathLike[str], mode: int | None = None) -> AttributePlatform: ...
    def at_entry(self, relative: str | bytes, mode: int | None = None) -> AttributePlatform: ...
    def attribute_matches(self) -> AttributeOutcome: ...
    def selected_attribute_matches(self, given: Sequence[str]) -> AttributeOutcome: ...
    def statistics(self) -> dict[str, Any]: ...
    def take_statistics(self) -> dict[str, Any]: ...

class AttributePlatform:
    def path(self) -> Path: ...
    def matching_exclude_pattern(self) -> ExcludeMatch | None: ...
    def is_excluded(self) -> bool: ...
    def excluded_kind(self) -> str | None: ...
    def matching_attributes(self, out: AttributeOutcome) -> bool: ...

class ExcludeMatch:
    @property
    def pattern(self) -> bytes: ...
    @property
    def source(self) -> Path | None: ...
    @property
    def sequence_number(self) -> int: ...
    @property
    def kind(self) -> str: ...
    def is_negative(self) -> bool: ...

class AttributeMatch:
    @property
    def pattern(self) -> bytes: ...
    @property
    def name(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def value(self) -> bytes | None: ...
    @property
    def kind(self) -> str: ...
    @property
    def source_id(self) -> int | None: ...
    @property
    def source(self) -> Path | None: ...
    @property
    def sequence_number(self) -> int: ...

class AttributeOutcome:
    def iter(self) -> AttributeMatches: ...
    def iter_selected(self) -> AttributeMatches: ...
    def is_done(self) -> bool: ...
    def reset(self) -> None: ...
    def match_by_id(self, id: int) -> AttributeMatch | None: ...

class AttributeMatches(Iterator[AttributeMatch]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> AttributeMatch: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class AttributeRepository:
    def attributes(self, index: IndexFile, attributes_source: str = "worktree_then_id_mapping", ignore_source: str = "worktree_then_id_mapping_if_not_skipped", exclude_overrides: IgnoreSearch | None = None) -> AttributeStack: ...
    def attributes_only(self, index: IndexFile, attributes_source: str = "worktree_then_id_mapping") -> AttributeStack: ...
    def excludes(self, index: IndexFile, overrides: IgnoreSearch | None = None, source: str = "worktree_then_id_mapping_if_not_skipped") -> AttributeStack: ...
