from collections.abc import Iterator
from typing import Any, Self
from ._gix import ObjectId, Rewrites
from ._objects import ObjectSpec, Time
from ._runtime import CancellationToken, Progress

class BlameOptions:
    def __init__(self, *, diff_algorithm: str | None = None, ranges: list[tuple[int, int]] | None = None, since: Time | None = None, rewrites: Rewrites | None = None) -> None: ...

class BlameEntry:
    @property
    def start_in_blamed_file(self) -> int: ...
    @property
    def start_in_source_file(self) -> int: ...
    @property
    def len(self) -> int: ...
    @property
    def commit_id(self) -> ObjectId: ...
    @property
    def source_file_name(self) -> bytes | None: ...
    def range_in_blamed_file(self) -> tuple[int, int]: ...
    def range_in_source_file(self) -> tuple[int, int]: ...

class BlameOutcome:
    @property
    def entries(self) -> list[BlameEntry]: ...
    @property
    def blob(self) -> bytes: ...
    @property
    def statistics(self) -> dict[str, int]: ...
    def entries_with_lines(self) -> BlameLines: ...

class BlameLines(Iterator[tuple[BlameEntry, list[bytes]]]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[BlameEntry, list[bytes]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class _RepositoryBlame:
    def blame_file(self, file_path: str | bytes, suspect: ObjectSpec, options: BlameOptions | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> BlameOutcome: ...
