from os import PathLike
from types import TracebackType
from typing import Self
from ._gix import ObjectId
from ._merge import MergeLabels
from ._objects import ObjectSpec
from ._runtime import Progress, CancellationToken

_Path = str | bytes | PathLike[str] | PathLike[bytes]

class BlobMergeOptions:
    def __init__(self, *, is_virtual_ancestor: bool = False, resolve_binary_with: str | None = None, diff_algorithm: str = "myers", conflict: str = "keep", conflict_style: str = "merge", marker_size: int = 7) -> None: ...
    @property
    def is_virtual_ancestor(self) -> bool: ...
    @property
    def resolve_binary_with(self) -> str | None: ...
    @property
    def diff_algorithm(self) -> str: ...
    @property
    def conflict(self) -> str: ...
    @property
    def conflict_style(self) -> str | None: ...
    @property
    def marker_size(self) -> int | None: ...

class MergeDriver:
    @property
    def name(self) -> bytes: ...
    @property
    def display_name(self) -> bytes: ...
    @property
    def command(self) -> bytes: ...
    @property
    def recursive(self) -> bytes | None: ...

class MergeResourceCache:
    default_driver: bytes | None
    filter_mode: str
    large_file_threshold_bytes: int
    def set_resource(self, id: ObjectSpec, mode: int, rela_path: str | bytes, kind: str) -> None: ...
    def drivers(self) -> list[MergeDriver]: ...
    def prepare_merge(self, options: BlobMergeOptions | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> PreparedMerge: ...

class MergeResource:
    @property
    def id(self) -> ObjectId: ...
    @property
    def rela_path(self) -> bytes: ...
    @property
    def kind(self) -> str: ...
    @property
    def size(self) -> int | None: ...
    @property
    def data(self) -> bytes | None: ...
    def as_slice(self) -> bytes | None: ...

class PreparedMerge:
    options: BlobMergeOptions
    driver: str | int
    @property
    def current(self) -> MergeResource: ...
    @property
    def ancestor(self) -> MergeResource: ...
    @property
    def other(self) -> MergeResource: ...
    def configured_driver(self) -> MergeDriver | str: ...
    def merge(self, labels: MergeLabels | None = None) -> tuple[bytes, str, str]: ...
    def builtin_merge(self, driver: str, labels: MergeLabels | None = None) -> tuple[bytes, str, str]: ...
    def buffer_by_pick(self, value: str) -> bytes | None: ...
    def id_by_pick(self, value: str, buffer: bytes) -> ObjectId | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class _RepositoryBlobMerge:
    def blob_merge_options(self) -> BlobMergeOptions: ...
    def merge_resource_cache(self, *, current_root: _Path | None = None, other_root: _Path | None = None, common_ancestor_root: _Path | None = None, progress: Progress | None = None, cancel: CancellationToken | None = None) -> MergeResourceCache: ...
