from ._network import Direction, Remote

class BranchRepository:
    def branch_names(self) -> list[str]: ...
    def branch_remote_ref_name(self, name: str | bytes, direction: Direction) -> bytes | None: ...
    def branch_remote_tracking_ref_name(self, name: str | bytes, direction: Direction) -> bytes | None: ...
    def branch_remote_name(self, short_branch_name: str | bytes, direction: Direction) -> bytes | None: ...
    def branch_remote(self, short_branch_name: str | bytes, direction: Direction) -> Remote | None: ...
    def upstream_branch_and_remote_for_tracking_branch(self, tracking_branch: str | bytes) -> tuple[bytes, Remote] | None: ...

class BranchReference:
    def remote_name(self, direction: Direction) -> bytes | None: ...
    def remote(self, direction: Direction) -> Remote | None: ...
    def remote_ref_name(self, direction: Direction) -> bytes | None: ...
    def remote_tracking_ref_name(self, direction: Direction) -> bytes | None: ...

class BranchHead:
    def into_remote(self, direction: Direction) -> Remote | None: ...
