from pathlib import Path
from ._index import IndexFile
from ._objects import Signature

class Compression:
    def level(self) -> int: ...

class FilesystemCapabilities:
    @property
    def precompose_unicode(self) -> bool: ...
    @property
    def ignore_case(self) -> bool: ...
    @property
    def executable_bit(self) -> bool: ...
    @property
    def symlink(self) -> bool: ...

class StatOptions:
    @property
    def trust_ctime(self) -> bool: ...
    @property
    def check_stat(self) -> bool: ...
    @property
    def use_nsec(self) -> bool: ...
    @property
    def use_stdev(self) -> bool: ...

class IgnorePatternParser:
    @property
    def support_precious(self) -> bool: ...

class SshConnectOptions:
    @property
    def command(self) -> str | None: ...
    @property
    def disallow_shell(self) -> bool: ...
    @property
    def kind(self) -> str | None: ...

class CommandContext:
    @property
    def git_dir(self) -> Path | None: ...
    @property
    def worktree_dir(self) -> Path | None: ...
    @property
    def no_replace_objects(self) -> bool | None: ...
    @property
    def ref_namespace(self) -> bytes | None: ...
    @property
    def literal_pathspecs(self) -> bool | None: ...
    @property
    def glob_pathspecs(self) -> bool | None: ...
    @property
    def icase_pathspecs(self) -> bool | None: ...
    @property
    def stderr(self) -> bool | None: ...

class _RepositoryConfigQueries:
    def git_dir_trust(self) -> str: ...
    def modules_path(self) -> Path | None: ...
    def install_dir(self) -> Path: ...
    def committer_or_set_fallback(self, name: str | bytes, email: str | bytes) -> Signature: ...
    def committer_or_set_generic_fallback(self) -> Signature: ...
    def loose_compression(self) -> Compression: ...
    def pack_compression(self) -> Compression: ...
    def editor(self) -> str | None: ...
    def filesystem_options(self) -> FilesystemCapabilities: ...
    def stat_options(self) -> StatOptions: ...
    def compute_object_cache_size_for_tree_diffs(self, index: IndexFile) -> int: ...
    def ignore_pattern_parser(self) -> IgnorePatternParser: ...
    def command_context(self) -> CommandContext: ...
    def diff_algorithm(self) -> str: ...
    def ssh_connect_options(self) -> SshConnectOptions: ...
