from pathlib import Path
from os import PathLike
from typing import Any, Iterable, Self
from ._gix import Repository, OpenOptions
from ._objects import Signature

class ConfigFile:
    def string(self, key: str) -> bytes | None: ...
    def boolean(self, key: str) -> bool | None: ...
    def integer(self, key: str) -> int | None: ...
    def set_raw_value(self, key: str, value: str | bytes) -> bytes | None: ...
    def to_bstring(self) -> bytes: ...

class ConfigSnapshot:
    def boolean(self, key: str) -> bool | None: ...
    def try_boolean(self, key: str) -> bool | None: ...
    def integer(self, key: str) -> int | None: ...
    def try_integer(self, key: str) -> int | None: ...
    def string(self, key: str) -> bytes | None: ...
    def trusted_path(self, key: str) -> Path | None: ...
    def plumbing(self) -> ConfigFile: ...

class ConfigSnapshotMut:
    def append_config(self, values: Iterable[str | bytes], source: str = "api") -> None: ...
    def set_raw_value(self, key: str, value: str | bytes) -> bytes | None: ...
    def string(self, key: str) -> bytes | None: ...
    def commit(self) -> Repository: ...
    def forget(self) -> ConfigFile: ...
    def commit_auto_rollback(self) -> ConfigRollback: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class ConfigRollback:
    @property
    def repo(self) -> Repository: ...
    def rollback(self) -> Repository: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class ConfigFileTransaction:
    def set_raw_value(self, key: str, value: str | bytes) -> bytes | None: ...
    def string(self, key: str) -> bytes | None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class _RepositoryConfig:
    def config_snapshot(self) -> ConfigSnapshot: ...
    def config_snapshot_mut(self) -> ConfigSnapshotMut: ...
    def config_file_mut(self, path: str | bytes | PathLike[str] | PathLike[bytes]) -> ConfigFileTransaction: ...
    def config_path(self, source: str) -> Path: ...
    def author(self) -> Signature | None: ...
    def committer(self) -> Signature | None: ...
    def big_file_threshold(self) -> int: ...
    def open_options(self) -> OpenOptions: ...
