from collections.abc import Iterator
from os import PathLike
from typing import Any, Self

from ._gix import ObjectId, Rewrites
from ._objects import ObjectSpec, Tree
from ._runtime import CancellationToken, Progress

class DiffOptions:
    def __init__(self) -> None: ...
    def no_locations(self) -> Self: ...
    def track_filename(self) -> Self: ...
    def track_path(self) -> Self: ...
    def track_rewrites(self, rewrites: Rewrites | None) -> Self: ...
    def with_rewrites(self, rewrites: Rewrites | None) -> Self: ...

class DiffLineStats:
    @property
    def removals(self) -> int: ...
    @property
    def insertions(self) -> int: ...
    @property
    def before(self) -> int: ...
    @property
    def after(self) -> int: ...
    @property
    def similarity(self) -> float: ...

class DiffStats:
    @property
    def files_changed(self) -> int: ...
    @property
    def lines_added(self) -> int: ...
    @property
    def lines_removed(self) -> int: ...

class TreeChange:
    @property
    def kind(self) -> str: ...
    def location(self) -> bytes: ...
    def source_location(self) -> bytes: ...
    def id(self) -> ObjectId: ...
    def entry_mode(self) -> int: ...
    @property
    def details(self) -> dict[str, Any]: ...
    def diff(self, resource_cache: DiffResourceCache) -> BlobDiff: ...

class DiffResourceCache:
    def set_resource(self, id: ObjectSpec, mode: int, rela_path: str | bytes, kind: str) -> None: ...
    def resource(self, kind: str) -> DiffResource | None: ...
    def prepare_diff(self) -> PreparedDiff: ...
    def clear_resource_cache(self) -> None: ...
    def clear_resource_cache_keep_allocation(self) -> int: ...

class DiffResource:
    @property
    def id(self) -> ObjectId: ...
    @property
    def mode(self) -> int: ...
    @property
    def driver_index(self) -> int | None: ...
    @property
    def is_derived(self) -> bool: ...
    @property
    def kind(self) -> str: ...
    @property
    def binary_size(self) -> int | None: ...
    @property
    def rela_path(self) -> bytes: ...
    @property
    def data(self) -> bytes | None: ...

class PreparedDiff:
    @property
    def old(self) -> DiffResource: ...
    @property
    def new(self) -> DiffResource: ...
    @property
    def operation(self) -> str: ...
    @property
    def algorithm(self) -> str | None: ...
    @property
    def old_or_new_is_derived(self) -> bool: ...
    @property
    def command(self) -> bytes | None: ...

class DiffHunk:
    @property
    def before(self) -> tuple[int, int]: ...
    @property
    def after(self) -> tuple[int, int]: ...
    @property
    def lines_before(self) -> tuple[bytes, ...]: ...
    @property
    def lines_after(self) -> tuple[bytes, ...]: ...

class DiffHunks(Iterator[DiffHunk]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> DiffHunk: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class BlobDiff:
    def line_counts(self) -> DiffLineStats | None: ...
    def lines(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> DiffHunks: ...

class TreeDiff:
    def options(self, options: DiffOptions) -> TreeDiff: ...
    def for_each_to_obtain_tree(self, other: Tree, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> TreeChanges: ...
    def for_each_to_obtain_tree_with_cache(self, other: Tree, resource_cache: DiffResourceCache, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> TreeChanges: ...
    def stats(self, other: Tree) -> DiffStats: ...

class TreeChanges(Iterator[TreeChange]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> TreeChange: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class DiffRepository:
    def diff_tree_to_tree(self, old_tree: Tree | None = None, new_tree: Tree | None = None, options: DiffOptions | None = None) -> list[TreeChange]: ...
    def diff_resource_cache(self, mode: str = "to_git", *, old_root: str | PathLike[str] | None = None, new_root: str | PathLike[str] | None = None) -> DiffResourceCache: ...
    def diff_resource_cache_for_tree_diff(self) -> DiffResourceCache: ...
