class Rewrites:
    def __init__(self, *, percentage: float | None = 0.5, limit: int = 1000, track_empty: bool = False, copies: bool = False, copy_percentage: float | None = 0.5, all_sources: bool = False) -> None: ...
    @property
    def percentage(self) -> float | None: ...
    @property
    def limit(self) -> int: ...
    @property
    def track_empty(self) -> bool: ...
