from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any, Self

from ._attributes import AttributeStack
from ._index import IndexFile
from ._pathspec import Pathspec
from ._runtime import CancellationToken, Progress

class DirwalkOptions:
    def empty_patterns_match_prefix(self, toggle: bool) -> DirwalkOptions: ...
    def recurse_repositories(self, toggle: bool) -> DirwalkOptions: ...
    def emit_pruned(self, toggle: bool) -> DirwalkOptions: ...
    def emit_ignored(self, value: str | None) -> DirwalkOptions: ...
    def emit_untracked(self, value: str) -> DirwalkOptions: ...
    def emit_tracked(self, toggle: bool) -> DirwalkOptions: ...
    def emit_empty_directories(self, toggle: bool) -> DirwalkOptions: ...
    def classify_untracked_bare_repositories(self, toggle: bool) -> DirwalkOptions: ...
    def symlinks_to_directories_are_ignored_like_directories(self, toggle: bool) -> DirwalkOptions: ...
    def emit_collapsed(self, value: str | None) -> DirwalkOptions: ...
    def for_deletion(self, value: str | None) -> DirwalkOptions: ...

class DirwalkEntry:
    @property
    def rela_path(self) -> bytes: ...
    @property
    def status(self) -> str: ...
    @property
    def property(self) -> str | None: ...
    @property
    def disk_kind(self) -> str | None: ...
    @property
    def index_kind(self) -> str | None: ...
    @property
    def pathspec_match(self) -> str | None: ...

class DirwalkItem:
    @property
    def entry(self) -> DirwalkEntry: ...
    @property
    def collapsed_directory_status(self) -> str | None: ...

class DirwalkStatistics:
    @property
    def read_dir_calls(self) -> int: ...
    @property
    def returned_entries(self) -> int: ...
    @property
    def seen_entries(self) -> int: ...

class DirwalkOutcome:
    @property
    def index(self) -> IndexFile: ...
    @property
    def pathspec(self) -> Pathspec: ...
    @property
    def excludes(self) -> AttributeStack: ...
    @property
    def traversal_root(self) -> Path: ...
    @property
    def dirwalk(self) -> DirwalkStatistics: ...

class DirwalkIter(Iterator[DirwalkItem]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> DirwalkItem: ...
    def into_outcome(self) -> DirwalkOutcome | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class DirwalkRepository:
    def dirwalk_options(self) -> DirwalkOptions: ...
    def dirwalk_iter(self, index: IndexFile, patterns: Sequence[str | bytes], options: DirwalkOptions, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> DirwalkIter: ...
