from os import PathLike
from typing import Any, Self

from ._gix import ObjectId
from ._index import IndexFile
from ._objects import ObjectSpec
from ._runtime import CancellationToken, Progress

class FileMetadata:
    def len(self) -> int: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    def readonly(self) -> bool: ...
    def modified(self) -> float: ...
    def accessed(self) -> float: ...
    def created(self) -> float: ...

class FilterDriverContext:
    @property
    def ref_name(self) -> bytes | None: ...
    @ref_name.setter
    def ref_name(self, value: str | bytes | None) -> None: ...
    @property
    def treeish(self) -> ObjectId | None: ...
    @treeish.setter
    def treeish(self, value: ObjectSpec | None) -> None: ...
    @property
    def blob(self) -> ObjectId | None: ...
    @blob.setter
    def blob(self, value: ObjectSpec | None) -> None: ...

class FilterRead:
    def read(self, size: int = -1) -> bytes: ...
    def is_changed(self) -> bool: ...
    def is_delayed(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class FilterPipeline:
    def convert_to_git(self, src: bytes, rela_path: str | PathLike[str], index: IndexFile) -> FilterRead: ...
    def convert_to_worktree(self, src: bytes, rela_path: str | bytes, *, unknown_encoding: str = "ignore") -> FilterRead: ...
    def worktree_file_to_object(self, rela_path: str | bytes, index: IndexFile) -> tuple[ObjectId, str, FileMetadata] | None: ...
    def driver_context_mut(self) -> FilterDriverContext: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class FilterRepository:
    def filter_pipeline(self, tree_if_bare: ObjectSpec | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[FilterPipeline, IndexFile]: ...
