from ._branch import (
    BranchRepository as _BranchRepository
)
from ._config_queries import (
    Compression as Compression, FilesystemCapabilities as FilesystemCapabilities, StatOptions as StatOptions, IgnorePatternParser as IgnorePatternParser, SshConnectOptions as SshConnectOptions, CommandContext as CommandContext, _RepositoryConfigQueries as _RepositoryConfigQueries
)
from ._network import prepare_clone as prepare_clone, prepare_clone_bare as prepare_clone_bare
from ._network import (
    Direction as Direction, Tags as Tags, Shallow as Shallow, RefSpec as RefSpec, RefMapOptions as RefMapOptions, Remote as Remote, Connection as Connection, PrepareFetch as PrepareFetch, PrepareClone as PrepareClone, PrepareCheckout as PrepareCheckout, RefMap as RefMap, RemoteRef as RemoteRef, Handshake as Handshake, FetchOutcome as FetchOutcome, _RepositoryNetwork as _RepositoryNetwork
)
from ._submodule import (
    SubmoduleIgnore as SubmoduleIgnore, SubmoduleFetchRecurse as SubmoduleFetchRecurse, SubmoduleUpdate as SubmoduleUpdate, SubmoduleBranch as SubmoduleBranch, SubmoduleState as SubmoduleState, ModulesFile as ModulesFile, SubmoduleNames as SubmoduleNames, Submodule as Submodule, SubmoduleIter as SubmoduleIter, _RepositorySubmodule as _RepositorySubmodule
)
from ._worktree import (
    Worktree as Worktree, WorktreeProxy as WorktreeProxy, WorktreeRepositoryIter as WorktreeRepositoryIter, WorktreeHead as WorktreeHead, WorktreeRemoveForce as WorktreeRemoveForce, WorktreeRemoveOptions as WorktreeRemoveOptions, WorktreeRemoveTarget as WorktreeRemoveTarget, CheckoutOutcome as CheckoutOutcome, StreamSource as StreamSource, AdditionalEntry as AdditionalEntry, WorktreeStream as WorktreeStream, WorktreeStreamEntry as WorktreeStreamEntry, ArchiveOptions as ArchiveOptions, _RepositoryWorktree as _RepositoryWorktree
)
from ._filter import (
    FileMetadata as FileMetadata, FilterDriverContext as FilterDriverContext, FilterRead as FilterRead, FilterPipeline as FilterPipeline, FilterRepository as _FilterRepository
)
from ._attributes import (
    IgnoreSearch as IgnoreSearch, AttributeStack as AttributeStack, AttributePlatform as AttributePlatform, ExcludeMatch as ExcludeMatch, AttributeMatch as AttributeMatch, AttributeOutcome as AttributeOutcome, AttributeMatches as AttributeMatches, AttributeRepository as _AttributeRepository
)
from ._dirwalk import (
    DirwalkOptions as DirwalkOptions, DirwalkEntry as DirwalkEntry, DirwalkItem as DirwalkItem, DirwalkStatistics as DirwalkStatistics, DirwalkOutcome as DirwalkOutcome, DirwalkIter as DirwalkIter, DirwalkRepository as _DirwalkRepository
)
from ._pathspec import (
    PathspecPattern as PathspecPattern, PathspecMatch as PathspecMatch, PathspecPatterns as PathspecPatterns, PathspecEntries as PathspecEntries, PathspecSearch as PathspecSearch, Pathspec as Pathspec, PathspecDefaults as PathspecDefaults, PathspecRepository as _PathspecRepository
)
from ._merge import (
    TreatAsUnresolved as TreatAsUnresolved, TreeMergeOptions as TreeMergeOptions, CommitMergeOptions as CommitMergeOptions, MergeLabels as MergeLabels, MergeConflict as MergeConflict, MergeIndexEntry as MergeIndexEntry, ContentMerge as ContentMerge, TreeMergeOutcome as TreeMergeOutcome, CommitMergeOutcome as CommitMergeOutcome, VirtualMergeBase as VirtualMergeBase, _RepositoryMerge as _RepositoryMerge
)
from ._blame import (
    BlameOptions as BlameOptions, BlameEntry as BlameEntry, BlameOutcome as BlameOutcome, BlameLines as BlameLines, _RepositoryBlame as _RepositoryBlame
)
from ._notes import (
    Note as Note, Notes as Notes, NotesRefs as NotesRefs, _RepositoryNotes as _RepositoryNotes
)
from ._status import (
    SubmoduleStatus as SubmoduleStatus, StatusItem as StatusItem, StatusPlatform as StatusPlatform, StatusIter as StatusIter, StatusOutcome as StatusOutcome, StatusRepository as _StatusRepository
)
from ._diff import (
    DiffOptions as DiffOptions, DiffLineStats as DiffLineStats, DiffStats as DiffStats, TreeChange as TreeChange, DiffResourceCache as DiffResourceCache, DiffResource as DiffResource, PreparedDiff as PreparedDiff, DiffHunk as DiffHunk, DiffHunks as DiffHunks, BlobDiff as BlobDiff, TreeDiff as TreeDiff, TreeChanges as TreeChanges, DiffRepository as _DiffRepository
)
from ._diff_options import (
    Rewrites as Rewrites
)
from ._index import (
    IndexStat as IndexStat, IndexEntry as IndexEntry, IndexEntryMut as IndexEntryMut, IndexEntries as IndexEntries, IndexFile as IndexFile, IndexRepository as _IndexRepository
)
from os import PathLike
from typing import ClassVar, Self
from ._runtime import CancellationToken as CancellationToken, Progress as Progress
from ._objects import (
    Object as Object, Blob as Blob, Tree as Tree, Commit as Commit, Tag as Tag,
    TreeEntry as TreeEntry, TreeEntries as TreeEntries, ParentIds as ParentIds,
    Signature as Signature, Time as Time, Header as Header, CommitData as CommitData,
    TagData as TagData, TreeData as TreeData, TreeEditor as TreeEditor,
    ObjectRepository as _ObjectRepository,
)
from ._references import (
    Target as Target, PreviousValue as PreviousValue, RefLog as RefLog,
    LogChange as LogChange, Change as Change, RefEdit as RefEdit, Reference as Reference,
    Head as Head, ReferenceIterPlatform as ReferenceIterPlatform, ReferenceIter as ReferenceIter,
    ReflogIterPlatform as ReflogIterPlatform, ReflogLine as ReflogLine, ReflogIter as ReflogIter,
    _RepositoryReferences,
)
from ._config import (
    ConfigFile as ConfigFile, ConfigSnapshot as ConfigSnapshot, ConfigSnapshotMut as ConfigSnapshotMut,
    ConfigRollback as ConfigRollback, ConfigFileTransaction as ConfigFileTransaction, _RepositoryConfig,
)
from ._revision import (
    RevisionSpec as RevisionSpec, RevisionWalkPlatform as RevisionWalkPlatform,
    RevisionWalk as RevisionWalk, RevisionInfo as RevisionInfo, _RepositoryRevision,
)

_Path = str | bytes | PathLike[str] | PathLike[bytes]

__version__: str
__gix_revision__: str

class Error(Exception): ...
class FeatureUnavailableError(Error): ...
class CancelledError(Error): ...
def build_features() -> list[str]: ...

class HashKind:
    SHA1: ClassVar[HashKind | None]
    SHA256: ClassVar[HashKind | None]
    def __init__(self, name: str) -> None: ...
    def len_in_bytes(self) -> int: ...
    def len_in_hex(self) -> int: ...
    def null(self) -> ObjectId: ...
    def empty_blob(self) -> ObjectId: ...
    def empty_tree(self) -> ObjectId: ...
    @staticmethod
    def all() -> list[HashKind]: ...

class ObjectId:
    def __init__(self, hex: str | bytes) -> None: ...
    @staticmethod
    def from_hex(hex: str | bytes) -> ObjectId: ...
    def kind(self) -> HashKind: ...
    def is_null(self) -> bool: ...
    def as_bytes(self) -> bytes: ...
    def __bytes__(self) -> bytes: ...

class OpenOptions:
    def __init__(self) -> None: ...
    @staticmethod
    def isolated() -> OpenOptions: ...
    def config_overrides(self, values: list[str]) -> Self: ...
    def cli_overrides(self, values: list[str]) -> Self: ...
    def open_path_as_is(self, enable: bool) -> Self: ...
    def bail_if_untrusted(self, enable: bool) -> Self: ...
    def strict_config(self, enable: bool) -> Self: ...
    def lossy_config(self, enable: bool) -> Self: ...
    def open(self, path: _Path) -> Repository: ...

class Repository(_BranchRepository, _RepositoryConfigQueries, _RepositoryNetwork, _RepositorySubmodule, _RepositoryWorktree, _FilterRepository, _AttributeRepository, _DirwalkRepository, _PathspecRepository, _RepositoryMerge, _RepositoryBlame, _RepositoryNotes, _StatusRepository, _DiffRepository, _IndexRepository, _ObjectRepository, _RepositoryReferences, _RepositoryConfig, _RepositoryRevision):
    def git_dir(self) -> str: ...
    def path(self) -> str: ...
    def common_dir(self) -> str: ...
    def current_dir(self) -> str: ...
    def workdir(self) -> str | None: ...
    def work_dir(self) -> str | None: ...
    def index_path(self) -> str: ...
    def prefix(self) -> str | None: ...
    def is_bare(self) -> bool: ...
    def is_pristine(self) -> bool | None: ...
    def kind(self) -> str: ...
    def state(self) -> str | None: ...
    def object_hash(self) -> HashKind: ...
    def workdir_path(self, rela_path: str | bytes) -> str | None: ...
    def normalize_path(self, path: str | bytes) -> bytes: ...
    def set_workdir(self, workdir: _Path | None) -> str | None: ...
    def reload(self) -> Self: ...
    def object_cache_size(self, bytes: int | None) -> None: ...
    def object_cache_size_if_unset(self, bytes: int) -> None: ...
    def with_object_memory(self) -> Repository: ...

def open(path: _Path) -> Repository: ...
def open_opts(path: _Path, options: OpenOptions) -> Repository: ...
def discover(path: _Path) -> Repository: ...
def discover_opts(path: _Path, options: OpenOptions) -> Repository: ...
def init(path: _Path, *, object_hash: HashKind | None = None, options: OpenOptions | None = None, destination_must_be_empty: bool | None = None) -> Repository: ...
def init_bare(path: _Path, *, object_hash: HashKind | None = None, options: OpenOptions | None = None) -> Repository: ...
