from ._blame import (
    BlameOptions as BlameOptions, BlameEntry as BlameEntry, BlameOutcome as BlameOutcome, BlameLines as BlameLines, _RepositoryBlame as _RepositoryBlame
)
from ._notes import (
    Note as Note, Notes as Notes, NotesRefs as NotesRefs, _RepositoryNotes as _RepositoryNotes
)
from ._status import (
    SubmoduleStatus as SubmoduleStatus, StatusItem as StatusItem, StatusPlatform as StatusPlatform, StatusIter as StatusIter, StatusOutcome as StatusOutcome, StatusRepository as _StatusRepository
)
from ._diff import (
    DiffOptions as DiffOptions, DiffLineStats as DiffLineStats, DiffStats as DiffStats, TreeChange as TreeChange, DiffResourceCache as DiffResourceCache, DiffResource as DiffResource, PreparedDiff as PreparedDiff, DiffHunk as DiffHunk, DiffHunks as DiffHunks, BlobDiff as BlobDiff, TreeDiff as TreeDiff, TreeChanges as TreeChanges, DiffRepository as _DiffRepository
)
from ._diff_options import (
    Rewrites as Rewrites
)
from ._index import (
    IndexStat as IndexStat, IndexEntry as IndexEntry, IndexEntryMut as IndexEntryMut, IndexEntries as IndexEntries, IndexFile as IndexFile, IndexRepository as _IndexRepository
)
from os import PathLike
from typing import ClassVar, Self
from ._runtime import CancellationToken as CancellationToken, Progress as Progress
from ._objects import (
    Object as Object, Blob as Blob, Tree as Tree, Commit as Commit, Tag as Tag,
    TreeEntry as TreeEntry, TreeEntries as TreeEntries, ParentIds as ParentIds,
    Signature as Signature, Time as Time, Header as Header, CommitData as CommitData,
    TagData as TagData, TreeData as TreeData, TreeEditor as TreeEditor,
    ObjectRepository as _ObjectRepository,
)
from ._references import (
    Target as Target, PreviousValue as PreviousValue, RefLog as RefLog,
    LogChange as LogChange, Change as Change, RefEdit as RefEdit, Reference as Reference,
    Head as Head, ReferenceIterPlatform as ReferenceIterPlatform, ReferenceIter as ReferenceIter,
    ReflogIterPlatform as ReflogIterPlatform, ReflogLine as ReflogLine, ReflogIter as ReflogIter,
    _RepositoryReferences,
)
from ._config import (
    ConfigFile as ConfigFile, ConfigSnapshot as ConfigSnapshot, ConfigSnapshotMut as ConfigSnapshotMut,
    ConfigRollback as ConfigRollback, ConfigFileTransaction as ConfigFileTransaction, _RepositoryConfig,
)
from ._revision import (
    RevisionSpec as RevisionSpec, RevisionWalkPlatform as RevisionWalkPlatform,
    RevisionWalk as RevisionWalk, RevisionInfo as RevisionInfo, _RepositoryRevision,
)

_Path = str | bytes | PathLike[str] | PathLike[bytes]

__version__: str
__gix_revision__: str

class Error(Exception): ...
class FeatureUnavailableError(Error): ...
class CancelledError(Error): ...
def build_features() -> list[str]: ...

class HashKind:
    SHA1: ClassVar[HashKind | None]
    SHA256: ClassVar[HashKind | None]
    def __init__(self, name: str) -> None: ...
    def len_in_bytes(self) -> int: ...
    def len_in_hex(self) -> int: ...
    def null(self) -> ObjectId: ...
    def empty_blob(self) -> ObjectId: ...
    def empty_tree(self) -> ObjectId: ...
    @staticmethod
    def all() -> list[HashKind]: ...

class ObjectId:
    def __init__(self, hex: str | bytes) -> None: ...
    @staticmethod
    def from_hex(hex: str | bytes) -> ObjectId: ...
    def kind(self) -> HashKind: ...
    def is_null(self) -> bool: ...
    def as_bytes(self) -> bytes: ...
    def __bytes__(self) -> bytes: ...

class OpenOptions:
    def __init__(self) -> None: ...
    @staticmethod
    def isolated() -> OpenOptions: ...
    def config_overrides(self, values: list[str]) -> Self: ...
    def cli_overrides(self, values: list[str]) -> Self: ...
    def open_path_as_is(self, enable: bool) -> Self: ...
    def bail_if_untrusted(self, enable: bool) -> Self: ...
    def strict_config(self, enable: bool) -> Self: ...
    def lossy_config(self, enable: bool) -> Self: ...
    def open(self, path: _Path) -> Repository: ...

class Repository(_RepositoryBlame, _RepositoryNotes, _StatusRepository, _DiffRepository, _IndexRepository, _ObjectRepository, _RepositoryReferences, _RepositoryConfig, _RepositoryRevision):
    def git_dir(self) -> str: ...
    def path(self) -> str: ...
    def common_dir(self) -> str: ...
    def current_dir(self) -> str: ...
    def workdir(self) -> str | None: ...
    def work_dir(self) -> str | None: ...
    def index_path(self) -> str: ...
    def prefix(self) -> str | None: ...
    def is_bare(self) -> bool: ...
    def is_pristine(self) -> bool | None: ...
    def kind(self) -> str: ...
    def state(self) -> str | None: ...
    def object_hash(self) -> HashKind: ...
    def workdir_path(self, rela_path: str | bytes) -> str | None: ...
    def normalize_path(self, path: str | bytes) -> bytes: ...
    def set_workdir(self, workdir: _Path | None) -> str | None: ...
    def reload(self) -> Self: ...
    def object_cache_size(self, bytes: int | None) -> None: ...
    def object_cache_size_if_unset(self, bytes: int) -> None: ...
    def with_object_memory(self) -> Repository: ...

def open(path: _Path) -> Repository: ...
def open_opts(path: _Path, options: OpenOptions) -> Repository: ...
def discover(path: _Path) -> Repository: ...
def discover_opts(path: _Path, options: OpenOptions) -> Repository: ...
def init(path: _Path, *, object_hash: HashKind | None = None, options: OpenOptions | None = None, destination_must_be_empty: bool | None = None) -> Repository: ...
def init_bare(path: _Path, *, object_hash: HashKind | None = None, options: OpenOptions | None = None) -> Repository: ...
