from collections.abc import Iterable, Iterator
from typing import Any, ClassVar, Self
from ._gix import HashKind, ObjectId
from ._objects import Commit, ObjectSpec, Signature

class CommitGraph:
    def num_commits(self) -> int: ...
    def object_hash(self) -> HashKind: ...
    def id_at(self, position: int) -> ObjectId: ...
    def commit_at(self, position: int) -> CommitGraphCommit: ...
    def lookup(self, id: ObjectSpec) -> int | None: ...
    def commit_by_id(self, id: ObjectSpec) -> CommitGraphCommit | None: ...
    def iter_ids(self) -> CommitGraphIds: ...
    def iter_commits(self) -> CommitGraphCommits: ...

class CommitGraphCommit:
    def id(self) -> ObjectId: ...
    def committer_timestamp(self) -> int: ...
    def generation(self) -> int: ...
    def root_tree_id(self) -> ObjectId: ...
    def parent1(self) -> int | None: ...
    def iter_parents(self) -> CommitGraphParents: ...

class CommitGraphIds(Iterator[ObjectId]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> ObjectId: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class CommitGraphCommits(Iterator[CommitGraphCommit]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> CommitGraphCommit: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class CommitGraphParents(Iterator[int]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class RevisionGraph:
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def contains(self, id: ObjectSpec) -> bool: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...

class SelectRef:
    AnnotatedTags: ClassVar[SelectRef]
    AllTags: ClassVar[SelectRef]
    AllRefs: ClassVar[SelectRef]

class DescribePlatform:
    def names(self, select: SelectRef) -> Self: ...
    def traverse_first_parent(self, first_parent: bool) -> Self: ...
    def max_candidates(self, candidates: int) -> Self: ...
    def id_as_fallback(self, use_fallback: bool) -> Self: ...
    def try_resolve(self) -> DescribeResolution | None: ...
    def try_resolve_with_cache(self, cache: CommitGraph | None = None) -> DescribeResolution | None: ...
    def try_format(self) -> DescribeFormat | None: ...
    def format(self) -> DescribeFormat: ...

class DescribeResolution:
    @property
    def id(self) -> ObjectId: ...
    @property
    def name(self) -> bytes | None: ...
    @property
    def depth(self) -> int: ...
    @property
    def commits_seen(self) -> int: ...
    def format(self) -> DescribeFormat: ...
    def format_with_dirty_suffix(self, dirty_suffix: str | None = None) -> DescribeFormat: ...

class DescribeFormat:
    @property
    def id(self) -> ObjectId: ...
    @property
    def name(self) -> bytes | None: ...
    @property
    def depth(self) -> int: ...
    @property
    def hex_len(self) -> int: ...
    def is_exact_match(self) -> bool: ...
    def long(self, long: bool) -> Self: ...
    def __str__(self) -> str: ...

class Mailmap:
    def try_resolve(self, signature: Signature) -> Signature | None: ...
    def resolve(self, signature: Signature) -> Signature: ...
    def iter(self) -> MailmapEntries: ...
    def entries(self) -> list[MailmapEntry]: ...

class MailmapEntry:
    @property
    def new_name(self) -> bytes | None: ...
    @property
    def new_email(self) -> bytes | None: ...
    @property
    def old_name(self) -> bytes | None: ...
    @property
    def old_email(self) -> bytes: ...

class MailmapEntries(Iterator[MailmapEntry]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> MailmapEntry: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class SignedData:
    def to_bstring(self) -> bytes: ...

class SigningOptions:
    @property
    def format(self) -> str: ...
    @property
    def program(self) -> bytes: ...
    @property
    def signing_key(self) -> bytes: ...

class VerificationOutcome:
    def is_valid(self) -> bool: ...
    @property
    def format(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def trust_level(self) -> str: ...
    @property
    def signer(self) -> bytes | None: ...
    @property
    def key(self) -> bytes | None: ...
    @property
    def fingerprint(self) -> bytes | None: ...
    @property
    def primary_key_fingerprint(self) -> bytes | None: ...
    @property
    def output(self) -> bytes: ...
    @property
    def raw_output(self) -> bytes: ...

class _RepositoryHistory:
    def commit_graph(self) -> CommitGraph: ...
    def commit_graph_if_enabled(self) -> CommitGraph | None: ...
    def revision_graph(self, cache: CommitGraph | None = None) -> RevisionGraph: ...
    def merge_base_with_graph(self, one: ObjectSpec, two: ObjectSpec, graph: RevisionGraph) -> ObjectId | None: ...
    def merge_bases_many_with_graph(self, one: ObjectSpec, others: Iterable[ObjectSpec], graph: RevisionGraph) -> list[ObjectId]: ...
    def merge_base_octopus_with_graph(self, commits: Iterable[ObjectSpec], graph: RevisionGraph) -> ObjectId | None: ...
    def open_mailmap(self) -> Mailmap: ...
    def open_mailmap_into(self, target: Mailmap) -> None: ...
    def commit_signing_options(self) -> SigningOptions: ...
    def commit_signing_options_if_enabled(self) -> SigningOptions | None: ...

class _CommitHistory:
    def describe(self) -> DescribePlatform: ...
    def signature(self) -> tuple[bytes, SignedData] | None: ...
    def signed(self) -> Commit: ...
    def verify_signature(self) -> VerificationOutcome | None: ...
