from collections.abc import Iterator
from os import PathLike
from typing import Any, Self

from ._gix import HashKind, ObjectId
from ._objects import ObjectSpec
from ._runtime import CancellationToken, Progress

class IndexStat:
    def __init__(self, *, mtime: tuple[int, int] = (0, 0), ctime: tuple[int, int] = (0, 0), dev: int = 0, ino: int = 0, uid: int = 0, gid: int = 0, size: int = 0) -> None: ...
    @property
    def mtime(self) -> tuple[int, int]: ...
    @property
    def ctime(self) -> tuple[int, int]: ...
    @property
    def dev(self) -> int: ...
    @property
    def ino(self) -> int: ...
    @property
    def uid(self) -> int: ...
    @property
    def gid(self) -> int: ...
    @property
    def size(self) -> int: ...

class IndexEntry:
    @property
    def id(self) -> ObjectId: ...
    @property
    def flags(self) -> int: ...
    @property
    def mode(self) -> int: ...
    @property
    def stat(self) -> IndexStat: ...
    def path(self) -> bytes: ...
    def stage(self) -> int: ...
    def stage_raw(self) -> int: ...

class IndexEntryMut:
    id: ObjectId
    flags: int
    mode: int
    stat: IndexStat
    def path(self) -> bytes: ...
    def stage(self) -> int: ...
    def stage_raw(self) -> int: ...

class IndexEntries(Iterator[IndexEntry]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> IndexEntry: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class IndexFile:
    def path(self) -> PathLike[str]: ...
    def set_path(self, path: str | PathLike[str]) -> None: ...
    def object_hash(self) -> HashKind: ...
    def version(self) -> int: ...
    def timestamp(self) -> tuple[int, int]: ...
    def checksum(self) -> ObjectId | None: ...
    def is_sparse(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> IndexEntries: ...
    def entries(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> IndexEntries: ...
    def entry(self, position: int) -> IndexEntry: ...
    def entry_by_path(self, path: str | bytes) -> IndexEntry | None: ...
    def entry_by_path_and_stage(self, path: str | bytes, entry_stage: int) -> IndexEntry | None: ...
    def entry_mut_by_path_and_stage(self, path: str | bytes, entry_stage: int) -> IndexEntryMut | None: ...
    def entry_index_by_path_and_stage(self, path: str | bytes, entry_stage: int) -> int | None: ...
    def entry_range(self, path: str | bytes) -> tuple[int, int] | None: ...
    def prefixed_entries_range(self, prefix: str | bytes) -> tuple[int, int] | None: ...
    def path_is_directory(self, path: str | bytes) -> bool: ...
    def dangerously_push_entry(self, stat: IndexStat, id: ObjectId, flags: int, entry_mode: int, path: str | bytes) -> None: ...
    def sort_entries(self) -> None: ...
    def remove_entry_at_index(self, position: int) -> IndexEntry: ...
    def verify_entries(self) -> None: ...
    def verify_integrity(self) -> None: ...
    def write(self, *, skip_hash: bool = False, extensions: str = "all") -> None: ...

class IndexRepository:
    def open_index(self) -> IndexFile: ...
    def index(self) -> IndexFile: ...
    def try_index(self) -> IndexFile | None: ...
    def index_or_empty(self) -> IndexFile: ...
    def index_or_load_from_head(self) -> IndexFile: ...
    def index_or_load_from_head_or_empty(self) -> IndexFile: ...
    def index_from_tree(self, tree: ObjectSpec) -> IndexFile: ...
