from collections.abc import Iterable
from typing import Any, Self
from ._gix import ObjectId, Rewrites
from ._objects import ObjectSpec, TreeEditor
from ._index import IndexFile
from ._diff import TreeChange
from ._runtime import Progress, CancellationToken

class TreatAsUnresolved:
    @staticmethod
    def git() -> TreatAsUnresolved: ...
    @staticmethod
    def forced_resolution() -> TreatAsUnresolved: ...
    @staticmethod
    def undecidable() -> TreatAsUnresolved: ...

class TreeMergeOptions:
    def with_rewrites(self, rewrites: Rewrites | None) -> Self: ...
    def with_fail_on_conflict(self, how: TreatAsUnresolved | None) -> Self: ...
    def with_file_favor(self, favor: str | None) -> Self: ...
    def with_tree_favor(self, favor: str | None) -> Self: ...

class CommitMergeOptions:
    def __init__(self, tree_merge: TreeMergeOptions) -> None: ...
    def with_allow_missing_merge_base(self, allow: bool) -> Self: ...
    def with_use_first_merge_base(self, use_first: bool) -> Self: ...

class MergeLabels:
    def __init__(self, *, ancestor: str | bytes | None = None, current: str | bytes | None = None, other: str | bytes | None = None) -> None: ...

class MergeConflict:
    @property
    def ours(self) -> TreeChange: ...
    @property
    def theirs(self) -> TreeChange: ...
    @property
    def resolution(self) -> dict[str, Any]: ...
    def changes_in_resolution(self) -> tuple[TreeChange, TreeChange]: ...
    def is_unresolved(self, how: TreatAsUnresolved) -> bool: ...
    def entries(self) -> list[MergeIndexEntry | None]: ...
    def content_merge(self) -> ContentMerge | None: ...

class MergeIndexEntry:
    @property
    def id(self) -> ObjectId: ...
    @property
    def mode(self) -> int: ...

class ContentMerge:
    @property
    def merged_blob_id(self) -> ObjectId: ...
    @property
    def resolution(self) -> str: ...

class TreeMergeOutcome:
    @property
    def tree(self) -> TreeEditor: ...
    @property
    def conflicts(self) -> list[MergeConflict]: ...
    @property
    def failed_on_first_unresolved_conflict(self) -> bool: ...
    def has_unresolved_conflicts(self, how: TreatAsUnresolved) -> bool: ...
    def index_changed_after_applying_conflicts(self, index: IndexFile, how: TreatAsUnresolved, removal_mode: str = "prune") -> bool: ...

class CommitMergeOutcome:
    @property
    def tree_merge(self) -> TreeMergeOutcome: ...
    @property
    def merge_base_tree_id(self) -> ObjectId: ...
    @property
    def merge_bases(self) -> list[ObjectId] | None: ...
    @property
    def virtual_merge_bases(self) -> list[ObjectId]: ...

class VirtualMergeBase:
    @property
    def commit_id(self) -> ObjectId: ...
    @property
    def tree_id(self) -> ObjectId: ...
    @property
    def virtual_merge_bases(self) -> list[ObjectId]: ...

class _RepositoryMerge:
    def tree_merge_options(self) -> TreeMergeOptions: ...
    def merge_trees(self, ancestor_tree: ObjectSpec, our_tree: ObjectSpec, their_tree: ObjectSpec, labels: MergeLabels | None = None, options: TreeMergeOptions | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> TreeMergeOutcome: ...
    def merge_commits(self, our_commit: ObjectSpec, their_commit: ObjectSpec, labels: MergeLabels | None = None, options: CommitMergeOptions | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> CommitMergeOutcome: ...
    def virtual_merge_base(self, merge_bases: Iterable[ObjectSpec], options: TreeMergeOptions | None = None, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> VirtualMergeBase: ...
