from os import PathLike
from typing import ClassVar, Self
from ._gix import HashKind, ObjectId, OpenOptions, Repository
from ._runtime import CancellationToken, Progress
from ._worktree import CheckoutOutcome

_Path = str | bytes | PathLike[str] | PathLike[bytes]

class Direction:
    Fetch: ClassVar[Direction]
    Push: ClassVar[Direction]
    def as_str(self) -> str: ...

class Tags:
    All: ClassVar[Tags]
    Included: ClassVar[Tags]
    None_: ClassVar[Tags]

class Shallow:
    NoChange: ClassVar[Shallow]
    @staticmethod
    def DepthAtRemote(depth: int) -> Shallow: ...
    @staticmethod
    def Deepen(depth: int) -> Shallow: ...
    @staticmethod
    def Since(seconds: int) -> Shallow: ...
    @staticmethod
    def undo() -> Shallow: ...

class RefSpec:
    def __init__(self, spec: str | bytes, direction: Direction) -> None: ...
    def source(self) -> bytes | None: ...
    def destination(self) -> bytes | None: ...
    def allow_non_fast_forward(self) -> bool: ...
    def to_bstring(self) -> bytes: ...
    def __bytes__(self) -> bytes: ...

class RefMapOptions:
    def __init__(self, *, prefix_from_spec_as_filter_on_remote: bool = True, handshake_parameters: list[tuple[str, str | None]] | None = None, extra_refspecs: list[RefSpec] | None = None) -> None: ...

class Remote:
    def repo(self) -> Repository: ...
    def name(self) -> bytes | None: ...
    def url(self, direction: Direction) -> bytes | None: ...
    def refspecs(self, direction: Direction) -> list[RefSpec]: ...
    def fetch_tags(self) -> Tags: ...
    def with_fetch_tags(self, tags: Tags) -> Self: ...
    def with_refspecs(self, specs: list[RefSpec], direction: Direction) -> Self: ...
    def replace_refspecs(self, specs: list[RefSpec], direction: Direction) -> None: ...
    def rewrite_urls(self) -> None: ...
    def with_url(self, url: str | bytes) -> Self: ...
    def with_url_without_url_rewrite(self, url: str | bytes) -> Self: ...
    def with_push_url(self, url: str | bytes) -> Self: ...
    def with_push_url_without_url_rewrite(self, url: str | bytes) -> Self: ...
    def connect(self, direction: Direction, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> Connection: ...

class Connection:
    def ref_map(self, *, options: RefMapOptions | None = None, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[RefMap, Handshake]: ...
    def prepare_fetch(self, *, options: RefMapOptions | None = None, progress: Progress | None = None, cancel: CancellationToken | None = None) -> PrepareFetch: ...

class PrepareFetch:
    def ref_map(self) -> RefMap: ...
    def with_dry_run(self, enabled: bool) -> Self: ...
    def with_write_packed_refs_only(self, enabled: bool) -> Self: ...
    def with_shallow(self, shallow: Shallow) -> Self: ...
    def receive(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> FetchOutcome: ...

class PrepareClone:
    def with_remote_name(self, name: str | bytes) -> Self: ...
    def with_ref_name(self, name: str | bytes | None = None) -> Self: ...
    def with_revision(self, revision: str | bytes | None = None) -> Self: ...
    def with_shallow(self, shallow: Shallow) -> Self: ...
    def with_in_memory_config_overrides(self, values: list[str]) -> Self: ...
    def with_fetch_options(self, options: RefMapOptions) -> Self: ...
    def fetch_only(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[Repository, FetchOutcome]: ...
    def fetch_then_checkout(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[PrepareCheckout, FetchOutcome]: ...
    def persist(self) -> Repository: ...

class PrepareCheckout:
    def repo(self) -> Repository: ...
    def persist(self) -> Repository: ...
    def main_worktree(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[Repository, CheckoutOutcome]: ...

class RefMap:
    @property
    def object_hash(self) -> HashKind: ...
    @property
    def refspecs(self) -> list[RefSpec]: ...
    @property
    def extra_refspecs(self) -> list[RefSpec]: ...
    @property
    def remote_refs(self) -> list[RemoteRef]: ...
    def is_missing_required_mapping(self) -> bool: ...

class RemoteRef:
    def unpack(self) -> tuple[bytes, ObjectId | None, ObjectId | None]: ...

class Handshake:
    @property
    def server_protocol_version(self) -> str: ...
    @property
    def refs(self) -> list[RemoteRef] | None: ...

class FetchOutcome:
    @property
    def ref_map(self) -> RefMap: ...
    @property
    def handshake(self) -> Handshake: ...
    @property
    def status(self) -> str: ...

class _RepositoryNetwork:
    def remote_names(self) -> list[bytes]: ...
    def remote_default_name(self, direction: Direction) -> bytes | None: ...
    def remote_at(self, url: str | bytes) -> Remote: ...
    def remote_at_without_url_rewrite(self, url: str | bytes) -> Remote: ...
    def find_remote(self, name_or_url: str | bytes) -> Remote: ...
    def try_find_remote(self, name_or_url: str | bytes) -> Remote | None: ...
    def try_find_remote_without_url_rewrite(self, name_or_url: str | bytes) -> Remote | None: ...
    def find_default_remote(self, direction: Direction) -> Remote | None: ...
    def find_fetch_remote(self, name_or_url: str | bytes | None = None) -> Remote: ...

def prepare_clone(url: str | bytes, path: _Path, *, options: OpenOptions | None = None) -> PrepareClone: ...
def prepare_clone_bare(url: str | bytes, path: _Path, *, options: OpenOptions | None = None) -> PrepareClone: ...
