from collections.abc import Iterable, Iterator
from typing import Any, Self
from ._gix import ObjectId
from ._objects import Blob, ObjectSpec

class Note:
    @property
    def reference(self) -> bytes: ...
    @property
    def blob(self) -> Blob: ...

class Notes:
    def with_refs(self, refs: Iterable[str | bytes]) -> Self: ...
    def with_commit_message(self, message: str) -> Self: ...
    def default_ref(self) -> bytes | None: ...
    def refs(self) -> NotesRefs: ...
    def get(self, object: ObjectSpec) -> list[Note]: ...
    def replace(self, notes_ref: str | bytes, object: ObjectSpec, data: str | bytes) -> ObjectId | None: ...
    def replace_at_ref(self, notes_ref: str | bytes, object: ObjectSpec, data: str | bytes) -> ObjectId | None: ...
    def remove(self, notes_ref: str | bytes, object: ObjectSpec) -> ObjectId | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class NotesRefs(Iterator[bytes]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> bytes: ...

class _RepositoryNotes:
    def notes(self) -> Notes: ...
