from ._diff import TreeDiff
from collections.abc import Iterator, Sequence
from os import PathLike
from typing import Any, BinaryIO, Literal, Self, TypeAlias

from ._gix import ObjectId, PreviousValue, Reference
from ._runtime import CancellationToken, Progress
from ._revision import RevisionWalkPlatform

ObjectKind: TypeAlias = Literal["blob", "tree", "commit", "tag"]
EntryKind: TypeAlias = Literal["tree", "blob", "exe", "link", "commit"]
ObjectSpec: TypeAlias = ObjectId | Object | Blob | Tree | Commit | Tag | str | bytes

class Time:
    @property
    def seconds(self) -> int: ...
    @property
    def offset(self) -> int: ...

class Signature:
    def __init__(self, name: str | bytes, email: str | bytes, seconds: int, offset: int = 0) -> None: ...
    @property
    def name(self) -> bytes: ...
    @property
    def email(self) -> bytes: ...
    @property
    def time(self) -> Time: ...

class Object:
    @property
    def id(self) -> ObjectId: ...
    @property
    def kind(self) -> ObjectKind: ...
    @property
    def data(self) -> bytes: ...
    def try_into_blob(self) -> Blob: ...
    def try_into_tree(self) -> Tree: ...
    def try_into_commit(self) -> Commit: ...
    def try_into_tag(self) -> Tag: ...
    def into_blob(self) -> Blob: ...
    def into_tree(self) -> Tree: ...
    def into_commit(self) -> Commit: ...
    def into_tag(self) -> Tag: ...
    def peel_to_kind(self, kind: ObjectKind) -> Object: ...
    def peel_to_tree(self) -> Tree: ...
    def peel_to_commit(self) -> Commit: ...
    def peel_tags_to_end(self) -> Object: ...

class _TypedObject:
    @property
    def id(self) -> ObjectId: ...
    @property
    def kind(self) -> ObjectKind: ...
    @property
    def data(self) -> bytes: ...
    def into_object(self) -> Object: ...

class Blob(_TypedObject): ...

class Tree(_TypedObject):
    def changes(self) -> TreeDiff: ...
    def iter(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> TreeEntries: ...
    def __iter__(self) -> TreeEntries: ...
    def decode(self) -> TreeData: ...
    def find_entry(self, name: str | bytes) -> TreeEntry | None: ...
    def lookup_entry(self, path: Sequence[str | bytes]) -> TreeEntry | None: ...
    def lookup_entry_by_path(self, relative_path: str | PathLike[str]) -> TreeEntry | None: ...
    def edit(self) -> TreeEditor: ...

class Commit(_TypedObject):
    def ancestors(self) -> RevisionWalkPlatform: ...
    def decode(self) -> CommitData: ...
    def message_raw(self) -> bytes: ...
    def author(self) -> Signature: ...
    def committer(self) -> Signature: ...
    def time(self) -> Time: ...
    def tree_id(self) -> ObjectId: ...
    def tree(self) -> Tree: ...
    def parent_ids(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ParentIds: ...

class Tag(_TypedObject):
    def target_id(self) -> ObjectId: ...
    def tagger(self) -> Signature | None: ...
    def decode(self) -> TagData: ...

class Header:
    def kind(self) -> ObjectKind: ...
    def size(self) -> int: ...
    def num_deltas(self) -> int | None: ...

class CommitData:
    @property
    def tree(self) -> bytes: ...
    @property
    def parents(self) -> tuple[bytes, ...]: ...
    @property
    def author(self) -> bytes: ...
    @property
    def committer(self) -> bytes: ...
    @property
    def encoding(self) -> bytes | None: ...
    @property
    def message(self) -> bytes: ...
    @property
    def extra_headers(self) -> tuple[tuple[bytes, bytes], ...]: ...

class TagData:
    @property
    def target(self) -> bytes: ...
    @property
    def target_kind(self) -> ObjectKind: ...
    @property
    def name(self) -> bytes: ...
    @property
    def tagger(self) -> bytes | None: ...
    @property
    def message(self) -> bytes: ...
    @property
    def signature(self) -> bytes | None: ...

class TreeData:
    @property
    def entries(self) -> tuple[TreeEntry, ...]: ...

class TreeEntry:
    def filename(self) -> bytes: ...
    def mode(self) -> int: ...
    def kind(self) -> EntryKind: ...
    def id(self) -> ObjectId: ...
    def object_id(self) -> ObjectId: ...
    def object(self) -> Object: ...

class TreeEntries(Iterator[TreeEntry]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> TreeEntry: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class ParentIds(Iterator[ObjectId]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> ObjectId: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class TreeEditor:
    def upsert(self, rela_path: str | bytes, kind: EntryKind, id: ObjectSpec) -> Self: ...
    def remove(self, rela_path: str | bytes) -> Self: ...
    def remove_leaf(self, rela_path: str | bytes) -> Self: ...
    def get(self, rela_path: str | bytes) -> TreeEntry | None: ...
    def set_root(self, root: Tree) -> Self: ...
    def write(self) -> ObjectId: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class ObjectRepository:
    def edit_tree(self, id: ObjectSpec) -> TreeEditor: ...
    def find_header(self, id: ObjectSpec) -> Header: ...
    def try_find_header(self, id: ObjectSpec) -> Header | None: ...
    def find_object(self, id: ObjectSpec) -> Object: ...
    def try_find_object(self, id: ObjectSpec) -> Object | None: ...
    def find_blob(self, id: ObjectSpec) -> Blob: ...
    def find_tree(self, id: ObjectSpec) -> Tree: ...
    def find_commit(self, id: ObjectSpec) -> Commit: ...
    def find_tag(self, id: ObjectSpec) -> Tag: ...
    def has_object(self, id: ObjectSpec) -> bool: ...
    def write_blob(self, data: str | bytes) -> ObjectId: ...
    def write_blob_stream(self, stream: BinaryIO) -> ObjectId: ...
    def write_object(self, kind: ObjectKind, data: str | bytes) -> ObjectId: ...
    def empty_tree(self) -> Tree: ...
    def empty_blob(self) -> Blob: ...
    def tag(self, name: str, target: ObjectSpec, target_kind: ObjectKind, tagger: Signature | None, message: str, constraint: PreviousValue) -> Reference: ...
    def commit(self, reference: str | bytes, message: str, tree: ObjectSpec, parents: Sequence[ObjectSpec] = ()) -> ObjectId: ...
    def commit_as(self, committer: Signature, author: Signature, reference: str | bytes, message: str, tree: ObjectSpec, parents: Sequence[ObjectSpec] = ()) -> ObjectId: ...
    def new_commit(self, message: str, tree: ObjectSpec, parents: Sequence[ObjectSpec] = ()) -> Commit: ...
    def new_commit_as(self, committer: Signature, author: Signature, message: str, tree: ObjectSpec, parents: Sequence[ObjectSpec] = ()) -> Commit: ...
