from ._branch import BranchReference, BranchHead
from collections.abc import Iterator
from types import TracebackType
from typing import ClassVar, Self
from ._gix import CancellationToken, ObjectId, Progress
from ._objects import Blob, Commit, Object, Signature, Tag, Tree

_Bytes = str | bytes
_ObjectSpec = ObjectId | Object | Blob | Commit | Tag | Tree | str | bytes

class Target:
    @staticmethod
    def Object(id: ObjectId) -> Target: ...
    @staticmethod
    def Symbolic(name: _Bytes) -> Target: ...
    def try_id(self) -> ObjectId | None: ...
    def try_name(self) -> bytes | None: ...

class PreviousValue:
    Any: ClassVar[PreviousValue]
    MustExist: ClassVar[PreviousValue]
    MustNotExist: ClassVar[PreviousValue]
    @staticmethod
    def MustExistAndMatch(target: Target) -> PreviousValue: ...
    @staticmethod
    def ExistingMustMatch(target: Target) -> PreviousValue: ...

class RefLog:
    AndReference: ClassVar[RefLog]
    Only: ClassVar[RefLog]

class LogChange:
    def __init__(self) -> None: ...
    mode: RefLog
    force_create_reflog: bool
    @property
    def message(self) -> bytes: ...
    @message.setter
    def message(self, value: _Bytes) -> None: ...

class Change:
    @staticmethod
    def Update(log: LogChange, expected: PreviousValue, new: Target) -> Change: ...
    @staticmethod
    def Delete(expected: PreviousValue, log: RefLog) -> Change: ...
    def new_value(self) -> Target | None: ...
    def previous_value(self) -> Target | None: ...

class RefEdit:
    def __init__(self, name: _Bytes, change: Change) -> None: ...
    @staticmethod
    def update(name: _Bytes, new: Target, expected: PreviousValue, reflog_message: _Bytes) -> RefEdit: ...
    @staticmethod
    def update_with_log(name: _Bytes, new: Target, expected: PreviousValue, log: LogChange) -> RefEdit: ...
    @staticmethod
    def delete(name: _Bytes, expected: PreviousValue) -> RefEdit: ...
    @staticmethod
    def delete_with_log(name: _Bytes, expected: PreviousValue, log: RefLog) -> RefEdit: ...
    def with_deref(self, deref: bool) -> RefEdit: ...
    @property
    def name(self) -> bytes: ...
    @property
    def change(self) -> Change: ...
    deref: bool

class Reference(BranchReference):
    def name(self) -> bytes: ...
    def target(self) -> Target: ...
    def try_id(self) -> ObjectId | None: ...
    def id(self) -> ObjectId: ...
    def follow(self) -> Reference | None: ...
    def follow_to_object(self) -> ObjectId: ...
    def peel_to_id(self) -> ObjectId: ...
    def into_fully_peeled_id(self) -> ObjectId: ...
    def peel_to_kind(self, kind: str) -> Object: ...
    def peel_to_commit(self) -> Commit: ...
    def peel_to_tree(self) -> Tree: ...
    def peel_to_blob(self) -> Blob: ...
    def peel_to_tag(self) -> Tag: ...
    def set_target_id(self, id: _ObjectSpec, reflog_message: _Bytes) -> None: ...
    def delete(self) -> None: ...
    def log_exists(self) -> bool: ...
    def log_iter(self) -> ReflogIterPlatform: ...

class Head(BranchHead):
    def name(self) -> bytes: ...
    def referent_name(self) -> bytes | None: ...
    def is_detached(self) -> bool: ...
    def is_unborn(self) -> bool: ...
    def id(self) -> ObjectId | None: ...
    def try_into_referent(self) -> Reference | None: ...
    def try_peel_to_id(self) -> ObjectId | None: ...
    def try_into_peeled_id(self) -> ObjectId | None: ...
    def into_peeled_id(self) -> ObjectId: ...
    def peel_to_object(self) -> Object: ...
    def into_peeled_object(self) -> Object: ...
    def peel_to_commit(self) -> Commit: ...
    def log_iter(self) -> ReflogIterPlatform: ...
    def prior_checked_out_branches(self) -> list[tuple[bytes, ObjectId]] | None: ...

class ReferenceIterPlatform:
    def all(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...
    def local_branches(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...
    def remote_branches(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...
    def tags(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...
    def pseudo(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...
    def prefixed(self, prefix: _Bytes, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> ReferenceIter: ...

class ReferenceIter(Iterator[Reference]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> Reference: ...
    def peeled(self) -> Self: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class ReflogIterPlatform:
    def all(self) -> ReflogIter | None: ...
    def rev(self) -> ReflogIter | None: ...

class ReflogLine:
    @property
    def previous_oid(self) -> ObjectId: ...
    @property
    def new_oid(self) -> ObjectId: ...
    @property
    def signature(self) -> Signature: ...
    @property
    def message(self) -> bytes: ...

class ReflogIter(Iterator[ReflogLine]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> ReflogLine: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class _RepositoryReferences:
    def head(self) -> Head: ...
    def head_id(self) -> ObjectId: ...
    def head_name(self) -> bytes | None: ...
    def head_ref(self) -> Reference | None: ...
    def head_commit(self) -> Commit: ...
    def head_tree_id(self) -> ObjectId: ...
    def head_tree_id_or_empty(self) -> ObjectId: ...
    def head_tree(self) -> Tree: ...
    def find_reference(self, name: _Bytes) -> Reference: ...
    def try_find_reference(self, name: _Bytes) -> Reference | None: ...
    def references(self) -> ReferenceIterPlatform: ...
    def reference(self, name: _Bytes, target: _ObjectSpec, constraint: PreviousValue, log_message: _Bytes) -> Reference: ...
    def tag_reference(self, name: str, target: _ObjectSpec, constraint: PreviousValue) -> Reference: ...
    def edit_reference(self, edit: RefEdit) -> list[RefEdit]: ...
    def edit_references(self, edits: list[RefEdit]) -> list[RefEdit]: ...
    def edit_references_as(self, edits: list[RefEdit], committer: Signature | None = None) -> list[RefEdit]: ...
    def namespace(self) -> bytes | None: ...
    def set_namespace(self, namespace: _Bytes) -> bytes | None: ...
    def clear_namespace(self) -> bytes | None: ...
    def delete_local_branches(self, names: list[_Bytes]) -> list[bytes]: ...
    def delete_local_branches_if_unchanged(self, branches: list[tuple[_Bytes, Target]]) -> None: ...
