from pathlib import Path
from collections.abc import Iterable, Iterator
from typing import Any, Self
from ._gix import ObjectId
from ._objects import ObjectSpec, Commit
from ._runtime import Progress, CancellationToken

class RevisionSpec:
    def kind(self) -> str: ...
    def single(self) -> ObjectId | None: ...
    def path_and_mode(self) -> tuple[bytes, int] | None: ...

class RevisionWalkPlatform:
    def sorting(self, order: str = "breadth_first", *, cutoff: int | None = None) -> Self: ...
    def first_parent_only(self) -> Self: ...
    def use_commit_graph(self, toggle: bool | None) -> Self: ...
    def with_boundary(self, ids: Iterable[ObjectSpec]) -> Self: ...
    def with_hidden(self, tips: Iterable[ObjectSpec]) -> Self: ...
    def all(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> RevisionWalk: ...

class RevisionWalk(Iterator[RevisionInfo]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> RevisionInfo: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: Any) -> None: ...

class RevisionInfo:
    @property
    def id(self) -> ObjectId: ...
    @property
    def parent_ids(self) -> list[ObjectId]: ...
    @property
    def generation(self) -> int | None: ...
    @property
    def commit_time(self) -> int | None: ...
    def object(self) -> Commit: ...

class _RepositoryRevision:
    def rev_parse_single(self, spec: str | bytes) -> ObjectId: ...
    def rev_parse(self, spec: str | bytes) -> RevisionSpec: ...
    def rev_walk(self, tips: Iterable[ObjectSpec]) -> RevisionWalkPlatform: ...
    def merge_base(self, one: ObjectSpec, two: ObjectSpec) -> ObjectId | None: ...
    def merge_bases_many(self, one: ObjectSpec, others: Iterable[ObjectSpec]) -> list[ObjectId]: ...
    def merge_base_octopus(self, commits: Iterable[ObjectSpec]) -> ObjectId | None: ...
    def is_shallow(self) -> bool: ...
    def shallow_file(self) -> Path: ...
    def shallow_commits(self) -> list[ObjectId] | None: ...
