from typing import Any

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...

class Progress:
    def __init__(self) -> None: ...
    @property
    def state(self) -> str: ...
    def snapshot(self) -> dict[str, Any]: ...
