from collections.abc import Iterator, Sequence
from typing import Any, Self

from ._gix import ObjectId, Rewrites
from ._index import IndexFile
from ._objects import ObjectSpec
from ._runtime import CancellationToken, Progress

class SubmoduleStatus:
    def is_dirty(self) -> bool | None: ...
    @property
    def index_id(self) -> ObjectId | None: ...
    @property
    def checked_out_head_id(self) -> ObjectId | None: ...
    @property
    def state(self) -> dict[str, bool]: ...
    @property
    def changes(self) -> list[StatusItem] | None: ...

class StatusItem:
    @property
    def kind(self) -> str: ...
    def location(self) -> bytes: ...
    def summary(self) -> str | None: ...
    @property
    def details(self) -> dict[str, Any]: ...

class StatusPlatform:
    def untracked_files(self, value: str) -> Self: ...
    def index(self, index: IndexFile) -> Self: ...
    def head_tree(self, tree: ObjectSpec) -> Self: ...
    def index_worktree_rewrites(self, rewrites: Rewrites | None) -> Self: ...
    def tree_index_track_renames(self, rewrites: Rewrites | None) -> Self: ...
    def index_worktree_submodules(self, ignore: str | None = None, *, check_dirty: bool = False) -> Self: ...
    def index_worktree_options_mut(self, *, thread_limit: int | None = None, sorting: bool = False) -> Self: ...
    def dirwalk_options(self, *, emit_ignored: bool = False) -> Self: ...
    def into_iter(self, patterns: Sequence[str | bytes] = ()) -> StatusIter: ...
    def into_index_worktree_iter(self, patterns: Sequence[str | bytes] = ()) -> StatusIter: ...

class StatusIter(Iterator[StatusItem]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> StatusItem: ...
    def close(self) -> None: ...
    def outcome_mut(self) -> StatusOutcome | None: ...
    def into_outcome(self) -> StatusOutcome | None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class StatusOutcome:
    def has_changes(self) -> bool: ...
    def write_changes(self) -> bool: ...
    @property
    def worktree_index(self) -> IndexFile | None: ...

class StatusRepository:
    def status(self, progress: Progress | None = None, *, cancel: CancellationToken | None = None) -> StatusPlatform: ...
    def is_dirty(self) -> bool: ...
