from collections.abc import Iterator
from os import PathLike
from types import TracebackType
from typing import ClassVar, Self
from ._config import ConfigFile
from ._gix import ObjectId, Repository
from ._status import SubmoduleStatus

_Path = str | bytes | PathLike[str] | PathLike[bytes]

class SubmoduleIgnore:
    All: ClassVar[SubmoduleIgnore]
    Dirty: ClassVar[SubmoduleIgnore]
    Untracked: ClassVar[SubmoduleIgnore]
    None_: ClassVar[SubmoduleIgnore]

class SubmoduleFetchRecurse:
    OnDemand: ClassVar[SubmoduleFetchRecurse]
    Always: ClassVar[SubmoduleFetchRecurse]
    Never: ClassVar[SubmoduleFetchRecurse]

class SubmoduleUpdate:
    Checkout: ClassVar[SubmoduleUpdate]
    Rebase: ClassVar[SubmoduleUpdate]
    Merge: ClassVar[SubmoduleUpdate]
    None_: ClassVar[SubmoduleUpdate]
    @staticmethod
    def Command(value: str | bytes) -> SubmoduleUpdate: ...
    def command_bytes(self) -> bytes | None: ...

class SubmoduleBranch:
    CurrentInSuperproject: ClassVar[SubmoduleBranch]
    @staticmethod
    def Name(value: str | bytes) -> SubmoduleBranch: ...
    def name_bytes(self) -> bytes | None: ...

class SubmoduleState:
    @property
    def repository_exists(self) -> bool: ...
    @property
    def is_old_form(self) -> bool: ...
    @property
    def worktree_checkout(self) -> bool: ...
    @property
    def superproject_configuration(self) -> bool: ...

class ModulesFile:
    @staticmethod
    def from_bytes(data: bytes, path: _Path | None = None, config: ConfigFile | None = None) -> ModulesFile: ...
    def append_submodule_overrides(self, config: ConfigFile) -> Self: ...
    def config(self) -> ConfigFile: ...
    def config_path(self) -> str | None: ...
    def names(self) -> SubmoduleNames: ...
    def name_by_path(self, relative_path: str | bytes) -> bytes | None: ...
    def path(self, name: str | bytes) -> bytes: ...
    def url(self, name: str | bytes) -> bytes: ...
    def update(self, name: str | bytes) -> SubmoduleUpdate | None: ...
    def branch(self, name: str | bytes) -> SubmoduleBranch | None: ...
    def fetch_recurse(self, name: str | bytes) -> SubmoduleFetchRecurse | None: ...
    def ignore(self, name: str | bytes) -> SubmoduleIgnore | None: ...
    def shallow(self, name: str | bytes) -> bool | None: ...

class SubmoduleNames(Iterator[bytes]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class Submodule:
    def name(self) -> bytes: ...
    def validated_name(self) -> bytes: ...
    def path(self) -> bytes: ...
    def url(self) -> bytes: ...
    def update(self) -> SubmoduleUpdate | None: ...
    def branch(self) -> SubmoduleBranch | None: ...
    def fetch_recurse(self) -> SubmoduleFetchRecurse | None: ...
    def ignore(self) -> SubmoduleIgnore | None: ...
    def shallow(self) -> bool | None: ...
    def is_active(self) -> bool: ...
    def index_id(self) -> ObjectId | None: ...
    def head_id(self) -> ObjectId | None: ...
    def git_dir(self) -> str: ...
    def work_dir(self) -> str: ...
    def git_dir_try_old_form(self) -> str: ...
    def state(self) -> SubmoduleState: ...
    def open(self) -> Repository | None: ...
    def status(self, ignore: SubmoduleIgnore, check_dirty: bool) -> SubmoduleStatus: ...

class SubmoduleIter(Iterator[Submodule]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> Submodule: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class _RepositorySubmodule:
    def open_modules_file(self) -> ModulesFile | None: ...
    def modules(self) -> ModulesFile | None: ...
    def submodules(self) -> SubmoduleIter | None: ...
