from collections.abc import Iterator
from os import PathLike
from types import TracebackType
from typing import ClassVar, Self
from ._gix import CancellationToken, HashKind, ObjectId, Progress, Repository
from ._index import IndexFile
from ._attributes import AttributeStack, IgnoreSearch
from ._pathspec import Pathspec

_Path = str | bytes | PathLike[str] | PathLike[bytes]

class Worktree:
    def base(self) -> str: ...
    def is_main(self) -> bool: ...
    def is_locked(self) -> bool: ...
    def dot_git_exists(self) -> bool: ...
    def id(self) -> bytes | None: ...
    def lock_reason(self) -> bytes | None: ...
    def open_index(self) -> IndexFile: ...
    def index(self) -> IndexFile: ...
    def attributes(self, overrides: IgnoreSearch | None = None) -> AttributeStack: ...
    def attributes_only(self) -> AttributeStack: ...
    def pathspec(self, patterns: list[str | bytes]) -> Pathspec: ...

class WorktreeProxy:
    def git_dir(self) -> str: ...
    def id(self) -> bytes: ...
    def base(self) -> str: ...
    def is_locked(self) -> bool: ...
    def is_prunable(self) -> bool: ...
    def lock_reason(self) -> bytes | None: ...
    def into_repo(self) -> Repository: ...
    def into_repo_with_possibly_inaccessible_worktree(self) -> Repository: ...
    def remove(self, force: WorktreeRemoveForce | None = None, *, progress: Progress | None = None) -> None: ...

class WorktreeRepositoryIter(Iterator[Repository]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> Repository: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class WorktreeHead:
    @staticmethod
    def Attached(name: str | bytes) -> WorktreeHead: ...
    @staticmethod
    def Detached(id: ObjectId) -> WorktreeHead: ...

class WorktreeRemoveForce:
    Never: ClassVar[WorktreeRemoveForce]
    DiscardChanges: ClassVar[WorktreeRemoveForce]
    OverrideLock: ClassVar[WorktreeRemoveForce]

class WorktreeRemoveOptions:
    def __init__(self, *, thread_limit: int | None = None, max_retries: int = 2) -> None: ...

class WorktreeRemoveTarget:
    def base(self) -> str: ...
    def repository(self) -> Repository: ...
    def options(self, options: WorktreeRemoveOptions) -> Self: ...
    def remove(self, force: WorktreeRemoveForce | None = None) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class CheckoutOutcome:
    @property
    def files_updated(self) -> int: ...
    @property
    def bytes_written(self) -> int: ...
    @property
    def collisions(self) -> list[tuple[bytes, str]]: ...
    @property
    def errors(self) -> list[tuple[bytes, str]]: ...
    @property
    def delayed_paths_unknown(self) -> list[bytes]: ...
    @property
    def delayed_paths_unprocessed(self) -> list[bytes]: ...

class StreamSource:
    Null: ClassVar[StreamSource]
    @staticmethod
    def Memory(data: bytes) -> StreamSource: ...
    @staticmethod
    def Path(path: _Path) -> StreamSource: ...

class AdditionalEntry:
    def __init__(self, id: ObjectId, mode: int, relative_path: str | bytes, source: StreamSource) -> None: ...

class WorktreeStream:
    def next_entry(self) -> WorktreeStreamEntry | None: ...
    def add_entry(self, entry: AdditionalEntry) -> None: ...
    def add_entry_from_path(self, root: _Path, path: _Path, object_hash: HashKind) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class WorktreeStreamEntry:
    @property
    def id(self) -> ObjectId: ...
    @property
    def mode(self) -> int: ...
    def relative_path(self) -> bytes: ...
    def bytes_remaining(self) -> int | None: ...
    def read(self, size: int = -1) -> bytes: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...

class ArchiveOptions:
    def __init__(self, format: str = "internal", *, compression_level: int | None = None, tree_prefix: str | bytes | None = None, modification_time: int | None = None) -> None: ...

class _RepositoryWorktree:
    def worktree(self) -> Worktree | None: ...
    def worktrees(self) -> list[WorktreeProxy]: ...
    def worktrees_including_main(self, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> WorktreeRepositoryIter: ...
    def worktree_proxy_by_id(self, id: str | bytes) -> WorktreeProxy | None: ...
    def main_repo(self) -> Repository: ...
    def add_worktree(self, destination: _Path, head: WorktreeHead, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[Repository, CheckoutOutcome]: ...
    def prepare_remove_worktree(self, target: _Path, *, progress: Progress | None = None) -> WorktreeRemoveTarget: ...
    def remove_worktree(self, target: _Path, force: WorktreeRemoveForce | None = None, *, progress: Progress | None = None) -> None: ...
    def worktree_stream(self, id: ObjectId | str | bytes, *, progress: Progress | None = None, cancel: CancellationToken | None = None) -> tuple[WorktreeStream, IndexFile]: ...
    def worktree_archive(self, stream: WorktreeStream, out: _Path, options: ArchiveOptions | None = None) -> None: ...
